apiVersion: v1
kind: Pod
metadata:
  name: my-first-gpu-pod
  namespace: rehs-2026-chatbot
spec:
  restartPolicy: Never
  containers:
  - name: gpu-test
    image: nvidia/cuda:12.4.0-base-ubuntu22.04
    command: ["sleep", "3600"]
    resources:
      limits:
        nvidia.com/gpu: 1
        memory: 8Gi
        cpu: 2
      requests:
        nvidia.com/gpu: 1
        memory: 8Gi
        cpu: 2